function applyTheme(){document.body.classList.toggle('darkTheme',localStorage.getItem('theme')==='dark')}
applyTheme();window.addEventListener('storage',applyTheme);
function apiBase(){let p=window.location.pathname.replace(/index\.html$/,'');const i=p.lastIndexOf('/ui/');if(i>=0)return p.slice(0,i+4)+'api/';if(!p.endsWith('/'))p+='/';return p+'api/'}
const API=apiBase(),CSRF=document.querySelector('meta[name="zoraxy.csrf.Token"]').content,REPO='https://github.com/MiranoVerhoef/zoraxy-tunnel',IMAGE='ghcr.io/miranoverhoef/zoraxy-tunnel-client';
let STATUS={fingerprint:'',server_host:'',default_tag:'',version:'',control_port:9443},TUNNELS=[],CLIENT_STATS={},svcTunnelId=null,svcServiceId=null,confirmCb=null,installTunnelId=null,installServiceId=null;
const OPEN_TUNNELS=new Set(),OPEN_SERVICES=new Set();

async function api(path,opts={}){opts.headers=opts.headers||{};opts.headers['X-CSRF-Token']=CSRF;if(opts.body)opts.headers['Content-Type']='application/json';try{const r=await fetch(API+path,opts),text=await r.text();let data=null;if(text){try{data=JSON.parse(text)}catch{data={error:text}}}return{ok:r.ok,status:r.status,data}}catch{return{ok:false,status:0,data:null}}}
function esc(s){return String(s||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._h);t._h=setTimeout(()=>t.classList.remove('show'),1700)}
async function copyText(s){if(!s)return;try{await navigator.clipboard.writeText(s);toast('Copied')}catch{toast('Copy failed')}}
function copyFrom(id){copyText(document.getElementById(id).textContent)}
function closeModal(id){document.getElementById(id).classList.remove('show')}
function anyModalOpen(){return !!document.querySelector('.overlay.show')}
function inputFocused(){const a=document.activeElement;return a&&['INPUT','SELECT','TEXTAREA'].includes(a.tagName)}
function releaseBase(){return REPO+'/releases/download/'+(STATUS.version||'latest')+'/'}
function releasePage(){return REPO+'/releases/'+(STATUS.version?'tag/'+STATUS.version:'latest')}
function imageTag(){return STATUS.version||'latest'}

function normalizeEndpoint(raw){
  let s=String(raw||'').trim(),port=String(STATUS.control_port||9443);
  if(!s)return{ok:false,error:'Enter a public hostname or IP address.'};
  s=s.replace(/^https?:\/\//i,'').replace(/\/$/,'');
  if(/[\/?#\s]/.test(s))return{ok:false,error:'Use only a hostname/IP address and optional port.'};
  if(s.startsWith('[')){
    const end=s.indexOf(']');if(end<0)return{ok:false,error:'Invalid IPv6 address.'};
    const host=s.slice(0,end+1),rest=s.slice(end+1);
    if(!rest)return{ok:true,value:host+':'+port};
    if(!/^:\d+$/.test(rest))return{ok:false,error:'Invalid port.'};
    const p=Number(rest.slice(1));return p>0&&p<=65535?{ok:true,value:host+rest}:{ok:false,error:'Port must be between 1 and 65535.'};
  }
  const colons=(s.match(/:/g)||[]).length;
  if(colons===0)return{ok:true,value:s+':'+port};
  if(colons===1){const i=s.lastIndexOf(':'),host=s.slice(0,i),ps=s.slice(i+1),p=Number(ps);if(!host||!/^\d+$/.test(ps)||p<1||p>65535)return{ok:false,error:'Invalid hostname or port.'};return{ok:true,value:host+':'+p}}
  return{ok:true,value:'['+s+']:'+port};
}
function endpointFromStatus(){return normalizeEndpoint(STATUS.server_host)}
function updateEndpointPreview(){const input=document.getElementById('serverHost'),box=document.getElementById('endpointPreview'),r=normalizeEndpoint(input.value),b=box.querySelector('b');box.classList.toggle('invalid',!r.ok);b.textContent=r.ok?r.value:r.error;return r}
function openControlSetup(){const c=document.getElementById('controlCard');c.classList.add('open');localStorage.setItem('zte.controlOpen','1');setTimeout(()=>document.getElementById('serverHost').focus(),50)}
function toggleControl(){const c=document.getElementById('controlCard');c.classList.toggle('open');localStorage.setItem('zte.controlOpen',c.classList.contains('open')?'1':'0')}
if(localStorage.getItem('zte.controlOpen')==='1')document.getElementById('controlCard').classList.add('open');
function toggleTunnel(id){OPEN_TUNNELS.has(id)?OPEN_TUNNELS.delete(id):OPEN_TUNNELS.add(id);renderTunnels()}
function toggleService(tid,sid){const k=tid+':'+sid;OPEN_SERVICES.has(k)?OPEN_SERVICES.delete(k):OPEN_SERVICES.add(k);renderTunnels()}

function formatBytes(n){n=Number(n||0);if(n<1024)return n+' B';const u=['KB','MB','GB','TB'];let i=-1;do{n/=1024;i++}while(n>=1024&&i<u.length-1);return n.toFixed(n>=10?1:2)+' '+u[i]}
function formatAge(iso,prefix=''){if(!iso)return'—';const ms=Math.max(0,Date.now()-new Date(iso).getTime());let s=Math.floor(ms/1000),d=Math.floor(s/86400);s%=86400;let h=Math.floor(s/3600);s%=3600;let m=Math.floor(s/60);const p=[];if(d)p.push(d+'d');if(h)p.push(h+'h');if(m||!p.length)p.push(m+'m');return prefix+p.slice(0,2).join(' ')}
function formatDate(iso){if(!iso)return'—';const d=new Date(iso);return isNaN(d)?'—':d.toLocaleString()}
function platform(c){return[c?.os,c?.arch].filter(Boolean).join(' / ')||'—'}
function versionMismatch(c){return !!(c?.online&&c.version&&STATUS.version&&c.version!==STATUS.version)}

async function loadStatus(){
  const {data}=await api('status');if(!data)return;STATUS=data;
  document.getElementById('fingerprint').textContent=data.fingerprint||'—';
  const serverInput=document.getElementById('serverHost');if(document.activeElement!==serverInput)serverInput.value=data.server_host||'';
  const tagInput=document.getElementById('defaultTag');if(document.activeElement!==tagInput)tagInput.value=data.default_tag||'';
  document.getElementById('controlPort').textContent=':'+data.control_port;document.getElementById('ingressPort').textContent=':'+data.ingress_port;document.getElementById('defaultPortHelp').textContent=data.control_port;
  document.getElementById('versionPill').textContent=data.version||'—';document.getElementById('statOnline').textContent=data.online_count;document.getElementById('statTunnels').textContent=data.tunnel_count;document.getElementById('statControl').textContent=':'+data.control_port;document.getElementById('statIngress').textContent=':'+data.ingress_port;
  document.getElementById('onlineDot').classList.toggle('ok',data.online_count>0);document.getElementById('onlineText').textContent=data.online_count===1?'client online':'clients online';
  const ep=normalizeEndpoint(data.server_host);document.getElementById('controlHostBadge').textContent=ep.ok?ep.value:'not configured';document.getElementById('controlHostBadge').classList.toggle('warn',!ep.ok);document.getElementById('controlPortsBadge').textContent=':'+data.control_port+' / :'+data.ingress_port;document.getElementById('controlSummary').textContent=ep.ok?ep.value:'Configure the client endpoint';
  document.getElementById('setupBanner').classList.toggle('hidden',ep.ok);updateEndpointPreview();
}
async function saveSettings(){
  const ep=updateEndpointPreview();if(!ep.ok){openControlSetup();toast(ep.error);return}
  const default_tag=document.getElementById('defaultTag').value.trim();const {ok,data}=await api('settings',{method:'POST',body:JSON.stringify({server_host:ep.value,default_tag})});
  if(!ok){toast(data?.error||'Could not save settings');return}document.getElementById('serverHost').value=ep.value;toast('Control Node saved');await loadStatus();
}
async function loadTunnels(){const [tRes,cRes]=await Promise.all([api('tunnels'),api('client-stats')]);if(!tRes.ok){document.getElementById('tunnels').innerHTML='<div class="empty"><b>Could not load tunnels</b><span>Check the plugin status and try again.</span></div>';return}TUNNELS=tRes.data||[];CLIENT_STATS=cRes.ok&&cRes.data?cRes.data:{};renderTunnels()}
function renderTunnels(){const el=document.getElementById('tunnels');if(!TUNNELS.length){el.innerHTML='<div class="empty"><b>No tunnels yet</b><span>Create a tunnel to connect your first client.</span></div>';return}el.innerHTML='<div class="tunnel-list">'+TUNNELS.map(renderTunnel).join('')+'</div>'}

function renderClientPanel(t,c){
  if(!c||(!c.version&&!c.hostname&&!c.connected_at&&!c.remote_addr))return `<div class="client-panel"><div class="client-panel-head"><b>Client</b><span class="spacer"></span><span class="badge ${t.online?'warn':''}">${t.online?'legacy client':'no telemetry'}</span></div><div class="client-note">${t.online?'Update this client to '+esc(STATUS.version||'the latest version')+' to enable connection telemetry.':'Telemetry appears after the client connects.'}</div></div>`;
  const mismatch=versionMismatch(c),traffic=formatBytes((c.bytes_to_client||0)+(c.bytes_from_client||0));
  return `<div class="client-panel"><div class="client-panel-head"><b>${esc(c.hostname||'Client connection')}</b><span class="spacer"></span><span class="badge ${c.online?'ok':''}">${c.online?'online':'offline'}</span>${c.version?`<span class="badge ${mismatch?'warn':'ok'}">${esc(c.version)}</span>`:''}</div><div class="client-primary"><div class="primary-metric"><div class="metric-label">Uptime</div><div class="metric-value">${c.online?formatAge(c.connected_at):'—'}</div></div><div class="primary-metric"><div class="metric-label">Last activity</div><div class="metric-value">${c.last_activity?(c.online?formatAge(c.last_activity)+' ago':formatDate(c.last_activity)):'—'}</div></div><div class="primary-metric"><div class="metric-label">Requests</div><div class="metric-value">${Number(c.requests||0).toLocaleString()}</div></div><div class="primary-metric"><div class="metric-label">Traffic</div><div class="metric-value">${traffic}</div></div></div><div class="client-details"><div class="detail-line"><span>Platform</span><b>${esc(platform(c))}</b></div><div class="detail-line"><span>Remote</span><b class="mono">${esc(c.remote_addr||'—')}</b></div><div class="detail-line"><span>Streams</span><b>${Number(c.active_streams||0)}</b></div><div class="detail-line"><span>Reconnects</span><b>${Number(c.reconnect_count||0)}</b></div><div class="detail-line"><span>To client</span><b>${formatBytes(c.bytes_to_client)}</b></div><div class="detail-line"><span>From client</span><b>${formatBytes(c.bytes_from_client)}</b></div></div>${mismatch?`<div class="client-note warn">Client ${esc(c.version)} does not match plugin ${esc(STATUS.version)}.</div>`:'<div class="client-note">Session counters reset when the plugin restarts.</div>'}</div>`;
}
function renderTunnel(t){
  const services=t.services||[],open=OPEN_TUNNELS.has(t.id),c=CLIENT_STATS[t.id]||{},vBadge=c.version?`<span class="badge ${versionMismatch(c)?'warn':''}">${esc(c.version)}</span>`:'',upBadge=t.online&&c.connected_at?`<span class="badge">up ${formatAge(c.connected_at)}</span>`:'';
  return `<div class="tunnel ${open?'open':''}"><div class="tunnel-head" onclick="toggleTunnel('${t.id}')"><span class="status-dot ${t.online?'ok':''}"></span><div class="tunnel-main"><div class="tunnel-name">${esc(t.name)}</div><div class="tunnel-meta mono">${esc(t.id)} · token ${esc(t.token_hint||'—')}</div></div><div class="tunnel-badges"><span class="badge ${t.online?'ok':''}">${t.online?'online':'offline'}</span>${vBadge}${upBadge}<span class="badge">${services.length} service${services.length===1?'':'s'}</span><span class="badge">${t.enabled?'enabled':'disabled'}</span><span class="chev">⌄</span></div></div><div class="tunnel-body"><div class="tunnel-content">${renderClientPanel(t,c)}<div class="tunnel-actions"><button class="btn compact" onclick="event.stopPropagation();tunnelAction('${t.id}','regenerate')">New token</button><button class="btn compact ghost" onclick="event.stopPropagation();tunnelAction('${t.id}','toggle')">${t.enabled?'Disable tunnel':'Enable tunnel'}</button><button class="btn compact primary" onclick="event.stopPropagation();openSvc('${t.id}')">+ Register service</button><button class="btn compact danger" onclick="event.stopPropagation();askDelete('${t.id}')">Delete tunnel</button></div>${services.length?`<div class="service-list">${services.map(s=>renderService(t.id,s)).join('')}</div>`:'<div class="client-note">No services registered for this tunnel.</div>'}</div></div></div>`;
}
function renderService(tid,s){
  const installed=!!s.installed_route,key=tid+':'+s.id,open=OPEN_SERVICES.has(key),route=`${esc(s.host)}${s.path?esc(s.path):''} → ${esc(s.target)}`;
  return `<div class="service ${open?'open':''}"><div class="service-head" onclick="toggleService('${tid}','${s.id}')"><div class="service-main"><div class="service-title">${esc(s.name||s.host)}</div><div class="service-route mono">${route}</div></div><div class="service-badges"><span class="badge ${installed?'ok':'warn'}">${installed?'route installed':'route not installed'}</span>${s.skip_tls_verify?'<span class="badge warn">TLS verify off</span>':''}<span class="chev">⌄</span></div></div><div class="service-body"><div class="service-content"><div class="service-details"><div class="service-detail"><div class="k">Public host</div><div class="v mono">${esc(s.host)}${s.path?esc(s.path):''}</div></div><div class="service-detail"><div class="k">Client target</div><div class="v mono">${esc(s.target)}</div></div><div class="service-detail"><div class="k">Zoraxy TAG</div><div class="v">${esc(s.tag||'—')}</div></div><div class="service-detail"><div class="k">TLS verification</div><div class="v">${s.skip_tls_verify?'Skipped':'Enabled'}</div></div><div class="service-detail"><div class="k">Service state</div><div class="v">${s.enabled?'Enabled':'Disabled'}</div></div><div class="service-detail"><div class="k">Route</div><div class="v">${installed?'Installed':'Not installed'}</div></div></div><div class="service-actions">${installed?`<button class="btn compact" onclick="event.stopPropagation();svcAction('${tid}','${s.id}','uninstall')">Uninstall route</button>`:`<button class="btn compact primary" onclick="event.stopPropagation();askInstall('${tid}','${s.id}')">Install route</button>`}<button class="btn compact" onclick="event.stopPropagation();openSvc('${tid}','${s.id}')">Edit</button><button class="btn compact ghost" onclick="event.stopPropagation();svcAction('${tid}','${s.id}','toggle')">${s.enabled?'Disable':'Enable'}</button><button class="btn compact danger" onclick="event.stopPropagation();askDeleteService('${tid}','${s.id}')">Delete</button></div></div></div></div>`;
}

async function createTunnel(){const ep=endpointFromStatus();if(!ep.ok){openControlSetup();toast('Configure the Control Node endpoint first');return}const name=document.getElementById('newTunnel').value.trim();if(!name){toast('Enter a tunnel name');return}const {ok,data}=await api('tunnels',{method:'POST',body:JSON.stringify({name})});if(!ok||!data){toast(data?.error||'Could not create tunnel');return}document.getElementById('newTunnel').value='';if(data.tunnel?.id)OPEN_TUNNELS.add(data.tunnel.id);showCommands(data.token,true);await Promise.all([loadStatus(),loadTunnels()])}
async function tunnelAction(id,action){const {ok,data}=await api('tunnels/action',{method:'POST',body:JSON.stringify({id,action})});if(!ok){toast(data?.error||'Action failed');return}if(action==='regenerate'&&data?.token)showCommands(data.token,true);await Promise.all([loadStatus(),loadTunnels()])}
function openSvc(tid,sid=null){svcTunnelId=tid;svcServiceId=sid;const t=TUNNELS.find(x=>x.id===tid),s=sid&&t?(t.services||[]).find(x=>x.id===sid):null;document.getElementById('svcName').value=s?.name||'';document.getElementById('svcHost').value=s?.host||'';document.getElementById('svcPath').value=s?.path||'';document.getElementById('svcTarget').value=s?.target||'';document.getElementById('svcTag').value=s?s.tag||'':STATUS.default_tag||'';document.getElementById('svcSkipTLS').checked=!!s?.skip_tls_verify;document.getElementById('svcModalTitle').textContent=s?'Edit service':'Register service';document.getElementById('svcSubmitBtn').textContent=s?'Save changes':'Register service';document.getElementById('svcModal').classList.add('show')}
function closeSvc(){closeModal('svcModal');svcTunnelId=null;svcServiceId=null}
async function submitService(){const editing=!!svcServiceId,body={tunnel_id:svcTunnelId,service_id:svcServiceId||'',action:editing?'edit':'add',name:document.getElementById('svcName').value.trim(),host:document.getElementById('svcHost').value.trim(),path:document.getElementById('svcPath').value.trim(),target:document.getElementById('svcTarget').value.trim(),tag:document.getElementById('svcTag').value.trim(),skip_tls_verify:document.getElementById('svcSkipTLS').checked};if(!body.host||!body.target){toast('Public host and target are required');return}const {ok,data}=await api('services/action',{method:'POST',body:JSON.stringify(body)});if(!ok){toast(data?.error||'Could not save service');return}if(svcTunnelId)OPEN_TUNNELS.add(svcTunnelId);if(svcServiceId)OPEN_SERVICES.add(svcTunnelId+':'+svcServiceId);closeSvc();toast(editing?'Service updated':'Service registered');loadTunnels()}
async function svcAction(tid,sid,action){const {ok,data}=await api('services/action',{method:'POST',body:JSON.stringify({tunnel_id:tid,service_id:sid,action})});toast(ok?'Done':data?.error||'Action failed');OPEN_TUNNELS.add(tid);OPEN_SERVICES.add(tid+':'+sid);loadTunnels()}
function confirmDialog(title,msg,cb){document.getElementById('confirmTitle').textContent=title;document.getElementById('confirmMsg').textContent=msg;confirmCb=cb;document.getElementById('confirmModal').classList.add('show')}
function closeConfirm(){closeModal('confirmModal');confirmCb=null}
function runConfirm(){const cb=confirmCb;closeConfirm();if(cb)cb()}
function askDelete(id){const t=TUNNELS.find(x=>x.id===id);confirmDialog('Delete tunnel',`Delete ${t?.name||id}? Installed routes are removed automatically.`,async()=>{await api('tunnels/action',{method:'POST',body:JSON.stringify({id,action:'delete'})});OPEN_TUNNELS.delete(id);toast('Tunnel deleted');await Promise.all([loadStatus(),loadTunnels()])})}
function askDeleteService(tid,sid){const t=TUNNELS.find(x=>x.id===tid),s=t&&(t.services||[]).find(x=>x.id===sid);confirmDialog('Delete service',`Delete ${s?.name||s?.host||sid}?`,async()=>{await api('services/action',{method:'POST',body:JSON.stringify({tunnel_id:tid,service_id:sid,action:'delete'})});OPEN_SERVICES.delete(tid+':'+sid);toast('Service deleted');loadTunnels()})}
function askInstall(tid,sid){const t=TUNNELS.find(x=>x.id===tid),s=t&&(t.services||[]).find(x=>x.id===sid);installTunnelId=tid;installServiceId=sid;document.getElementById('installMsg').textContent=`Install a Zoraxy route for ${s?.host||''}?`;document.getElementById('installModal').classList.add('show')}
function closeInstall(){closeModal('installModal');installTunnelId=null;installServiceId=null}
async function doInstall(issue_cert){const tid=installTunnelId,sid=installServiceId;closeInstall();if(!tid)return;if(issue_cert)toast('Requesting certificate…');const {ok,data}=await api('services/action',{method:'POST',body:JSON.stringify({tunnel_id:tid,service_id:sid,action:'install',issue_cert})});toast(ok?(issue_cert?'Route and certificate installed':'Route installed'):data?.error||'Install failed');OPEN_TUNNELS.add(tid);OPEN_SERVICES.add(tid+':'+sid);loadTunnels()}

function showCommands(token,fresh){const ep=endpointFromStatus();if(!ep.ok){openControlSetup();toast('Configure the Control Node endpoint first');return}const host=ep.value,fp=STATUS.fingerprint||'',tok=token||'<TOKEN>',tag=imageTag();document.getElementById('cmd-cli').textContent=`tunnel-client \\\n  --server ${host} \\\n  --token ${tok} \\\n  --fingerprint "${fp}"`;document.getElementById('cmd-docker').textContent=`docker run -d --name tunnel-client --restart unless-stopped \\\n  --network host \\\n  ${IMAGE}:${tag} \\\n  --server ${host} --token ${tok} --fingerprint "${fp}"`;document.getElementById('cmd-compose').textContent=`services:\n  tunnel-client:\n    image: ${IMAGE}:${tag}\n    container_name: tunnel-client\n    restart: unless-stopped\n    network_mode: host\n    command:\n      - --server=${host}\n      - --token=${tok}\n      - --fingerprint=${fp}`;document.getElementById('tokenNote').innerHTML=fresh?'This token is shown <b>once</b>. Copy it now; only its hash is stored afterwards.':'Regenerate the token to reveal a new one.';switchTab('cli');document.getElementById('cmdModal').classList.add('show')}
function switchTab(tab){['cli','docker','compose'].forEach(t=>{document.getElementById('tab-'+t).style.display=t===tab?'block':'none';document.querySelector(`.tabs [data-tab="${t}"]`).classList.toggle('active',t===tab)})}
function openDownloads(){const base=releaseBase(),items=[['Linux x64','tunnel-client_linux_amd64'],['Linux ARM64','tunnel-client_linux_arm64'],['Windows x64','tunnel-client_windows_amd64.exe'],['Windows ARM64','tunnel-client_windows_arm64.exe'],['macOS Apple Silicon','tunnel-client_darwin_arm64'],['macOS Intel','tunnel-client_darwin_amd64']];document.getElementById('downloadLinks').innerHTML=items.map(([label,file])=>`<button class="btn" style="text-align:left" onclick="openExternal('${base}${file}')">${label}<span class="muted" style="float:right">${file}</span></button>`).join('')+`<button class="btn ghost" onclick="openExternal('${releasePage()}')">View all release assets</button>`;document.getElementById('downloadModal').classList.add('show')}
function openExternal(url){try{window.parent.open(url,'_blank','noopener,noreferrer')}catch{window.open(url,'_blank')}}
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.overlay.show').forEach(x=>x.classList.remove('show'))});
loadStatus().then(loadTunnels);setInterval(()=>{if(!anyModalOpen()&&!inputFocused())loadStatus().then(loadTunnels)},15000);
