let CURRENT_CMD_TOKEN='',CURRENT_CMD_FRESH=false,CURRENT_CMD_TUNNEL='';

function connectorList(c){return Array.isArray(c?.connectors)?c.connectors:[]}
function versionMismatch(c){return connectorList(c).some(x=>x.version&&STATUS.version&&x.version!==STATUS.version)||(!!c?.version&&!!STATUS.version&&c.version!==STATUS.version)}
function connectorCounts(c){const all=connectorList(c),online=all.filter(x=>x.online).length;return{all,online,total:all.length}}
function filteredTunnels(){
  const q=(document.getElementById('tunnelSearch')?.value||'').trim().toLowerCase(),filter=document.getElementById('tunnelFilter')?.value||'all';
  return TUNNELS.filter(t=>{const c=CLIENT_STATS[t.id]||{},state=tunnelState(t),services=t.services||[],connectors=connectorList(c);const hay=[t.name,t.id,...connectors.flatMap(x=>[x.id,x.hostname,x.os,x.arch,x.remote_addr]),...services.flatMap(s=>[s.name,s.host,s.target])].join(' ').toLowerCase();const qok=!q||hay.includes(q);const fok=filter==='all'||filter===state||(filter==='updates'&&versionMismatch(c));return qok&&fok})
}
function connectorRole(cn,c){if(!cn.online)return cn.preferred?'Preferred · offline':'Offline';if(cn.active&&cn.preferred)return'Primary · preferred';if(cn.active)return'Primary';if(cn.preferred)return'Preferred · standby';return'Standby'}
function connectorBadges(cn){let out='';if(cn.active)out+='<span class="connector-badge primary">Primary</span>';if(cn.preferred)out+='<span class="connector-badge preferred">Preferred</span>';if(!cn.online)out+='<span class="connector-badge offline">Offline</span>';if(cn.online&&!cn.active&&!cn.preferred)out+='<span class="connector-badge">Standby</span>';return out}
function renderConnectors(t,c){
  const list=connectorList(c),preferred=c.preferred_connector_id||'';
  if(!list.length)return '<div class="connector-section"><div class="connector-head"><strong>Connectors</strong><span>No connector telemetry yet. v1.8 clients report a stable connector ID.</span></div></div>';
  const rows=list.map(cn=>{const uptime=cn.online&&cn.connected_at?formatAge(cn.connected_at):'—',traffic=(cn.bytes_to_client||0)+(cn.bytes_from_client||0),plat=[cn.os,cn.arch].filter(Boolean).join(' / ')||'unknown',last=cn.last_activity?formatAge(cn.last_activity)+' ago':'—';return `<div class="connector-row"><div class="connector-identity"><strong><span class="status-dot ${cn.online?'ok':''}"></span>${esc(cn.hostname||cn.id)}</strong><span class="mono">${esc(cn.id)}</span><div class="connector-badges">${connectorBadges(cn)}</div></div><div class="connector-cell connector-platform">${esc(plat)}<small>${esc(cn.version||'version unknown')}</small></div><div class="connector-cell connector-uptime">${uptime}<small>${last}</small></div><div class="connector-cell connector-remote mono">${esc(cn.remote_addr||'—')}<small>${Number(cn.reconnect_count||0)} reconnects</small></div><div class="connector-cell connector-traffic">${formatBytes(traffic)}<small>↓ ${formatBytes(cn.bytes_from_client||0)} · ↑ ${formatBytes(cn.bytes_to_client||0)}</small></div><div class="connector-action">${cn.preferred?'<button class="btn secondary compact" disabled>Preferred</button>':`<button class="btn secondary compact" onclick="setPreferredConnector('${t.id}','${encodeURIComponent(cn.id)}')">Make preferred</button>`}</div></div>`}).join('');
  return `<div class="connector-section"><div class="connector-head"><strong>Connectors (${c.online_connector_count||0}/${list.length} online)</strong><span>${preferred?'Preferred connector automatically takes traffic again when it reconnects.':'Automatic sticky failover is active; the current primary remains selected while healthy.'}</span><div class="connector-spacer"></div>${preferred?`<button class="btn secondary compact" onclick="setPreferredConnector('${t.id}','')">Clear preference</button>`:''}</div>${rows}</div>`
}
async function setPreferredConnector(tid,encoded){const connector_id=encoded?decodeURIComponent(encoded):'';const {ok,data}=await api('connectors/preferred',{method:'POST',body:JSON.stringify({tunnel_id:tid,connector_id})});if(!ok){toast(data?.error||'Could not update preferred connector');return}toast(connector_id?'Preferred connector updated':'Connector preference cleared');OPEN_TUNNELS.add(tid);await loadTunnels()}

function renderTunnelGroup(t){
  const c=CLIENT_STATS[t.id]||{},services=t.services||[],state=tunnelState(t),open=OPEN_TUNNELS.has(t.id),traffic=(c.bytes_to_client||0)+(c.bytes_from_client||0),last=c.last_activity?(formatAge(c.last_activity)+' ago'):'—',uptime=t.online&&c.connected_at?formatAge(c.connected_at):'—',version=c.version||'—',update=versionMismatch(c),menuId='t-'+t.id,counts=connectorCounts(c),active=c.active_connector_id||'';
  const onlineText=!t.enabled?'Disabled':counts.total?`${counts.online}/${counts.total} online`:(t.online?'Online':'Offline');const status=`<span class="status-text ${t.online&&t.enabled?'':'offline'}"><span class="status-dot ${t.online&&t.enabled?'ok':''}"></span>${onlineText}</span>`;const activeName=connectorList(c).find(x=>x.id===active)?.hostname||active;
  return `<div class="tunnel-group ${open?'open':''}"><div class="tunnel-row"><div class="col-expand"><button class="expand-btn" onclick="event.stopPropagation();toggleTunnel('${t.id}')">›</button></div><div class="name-cell" onclick="toggleTunnel('${t.id}')"><div class="device-icon">▰</div><div class="name-stack"><strong>${esc(t.name)}</strong><span>${activeName?'Primary: '+esc(activeName):esc(platform(c))}</span></div></div><div class="cell">${status}</div><div class="cell">${services.length}</div><div class="cell">${uptime}</div><div class="cell ${update?'version-old':'muted'}">${esc(version)}${update?'<span class="tunnel-connector-summary">connector update available</span>':''}</div><div class="cell muted">${last}</div><div class="cell"><div class="traffic-main">${formatBytes(traffic)}</div><div class="traffic-sub"><span>↓ ${formatBytes(c.bytes_from_client||0)}</span><span>↑ ${formatBytes(c.bytes_to_client||0)}</span></div></div><div class="cell col-actions"><div class="manage-wrap"><button class="btn secondary compact manage-btn" onclick="toggleActionMenu('${menuId}',event)">Manage <span>⌄</span></button>${renderTunnelMenu(t,menuId,update)}</div></div></div><div class="tunnel-detail">${renderConnectors(t,c)}${renderServices(t)}</div></div>`
}

function defaultConnectorID(name){let id=String(name||'connector').trim().toLowerCase().replace(/[^a-z0-9._-]+/g,'-').replace(/^-+|-+$/g,'');if(!id)id='connector';return id+'-1'}
async function createTunnel(){const ep=endpointFromStatus();if(!ep.ok){closeModal('createTunnelModal');showTab('settings');toast('Configure the Control Node endpoint first');return}const name=document.getElementById('newTunnel').value.trim();if(!name){toast('Enter a tunnel name');return}const {ok,data}=await api('tunnels',{method:'POST',body:JSON.stringify({name})});if(!ok||!data){toast(data?.error||'Could not create tunnel');return}closeModal('createTunnelModal');if(data.tunnel?.id)OPEN_TUNNELS.add(data.tunnel.id);showCommands(data.token,true,data.tunnel?.name||name);await Promise.all([loadStatus(),loadTunnels()])}
async function tunnelAction(id,action){const {ok,data}=await api('tunnels/action',{method:'POST',body:JSON.stringify({id,action})});if(!ok){toast(data?.error||'Action failed');return}if(action==='regenerate'&&data?.token)showCommands(data.token,true,data.tunnel?.name||TUNNELS.find(x=>x.id===id)?.name||'connector');await Promise.all([loadStatus(),loadTunnels()])}
function showCommands(token,fresh,tunnelName=''){CURRENT_CMD_TOKEN=token||'<TOKEN>';CURRENT_CMD_FRESH=!!fresh;CURRENT_CMD_TUNNEL=tunnelName||CURRENT_CMD_TUNNEL||'connector';const field=document.getElementById('connectorId');if(field&&!field.value)field.value=defaultConnectorID(CURRENT_CMD_TUNNEL);refreshCommands();document.getElementById('tokenNote').innerHTML=fresh?'This credential is shown <b>once</b>. Reuse the same token for redundant connectors, but give every host a unique <b>connector ID</b>. Normal updates use <b>:latest</b> and do not change the token.':'Regenerate the credential only when you intentionally want to revoke the old one.';switchTab('compose');document.getElementById('cmdModal').classList.add('show')}
function refreshCommands(){const ep=endpointFromStatus();if(!ep.ok)return;const host=ep.value,fp=STATUS.fingerprint||'',tok=CURRENT_CMD_TOKEN||'<TOKEN>',raw=document.getElementById('connectorId')?.value||defaultConnectorID(CURRENT_CMD_TUNNEL),cid=raw.trim()||'connector-1';document.getElementById('cmd-cli').textContent=`tunnel-client \\\n  --server ${host} \\\n  --token ${tok} \\\n  --fingerprint "${fp}" \\\n  --connector-id ${cid}`;document.getElementById('cmd-docker').textContent=`docker run -d --name tunnel-client --restart unless-stopped --pull always \\\n  --network host \\\n  ${IMAGE}:latest \\\n  --server ${host} --token ${tok} --fingerprint "${fp}" --connector-id ${cid}`;document.getElementById('cmd-compose').textContent=`services:\n  tunnel-client:\n    image: ${IMAGE}:latest\n    pull_policy: always\n    container_name: tunnel-client\n    restart: unless-stopped\n    network_mode: host\n    command:\n      - --server=${host}\n      - --token=${tok}\n      - --fingerprint=${fp}\n      - --connector-id=${cid}`}

(function initFloatingMenus(){const layer=document.getElementById('floatingMenuLayer');if(!layer)return;let anchorRect=null,floating=null;function closeFloating(){layer.innerHTML='';floating=null;anchorRect=null}function positionFloating(){if(!floating||!anchorRect)return;const margin=10,gap=6,r=floating.getBoundingClientRect();let left=Math.max(margin,Math.min(anchorRect.right-r.width,window.innerWidth-r.width-margin)),top=anchorRect.bottom+gap;if(top+r.height>window.innerHeight-margin&&anchorRect.top-r.height-gap>=margin)top=anchorRect.top-r.height-gap;top=Math.max(margin,Math.min(top,window.innerHeight-r.height-margin));floating.style.left=Math.round(left)+'px';floating.style.top=Math.round(top)+'px'}function mirrorOpenMenu(){const open=document.querySelector('.table-wrap .menu.open');if(!open){closeFloating();return}floating=document.createElement('div');floating.className='floating-action-menu';floating.innerHTML=open.innerHTML;layer.innerHTML='';layer.appendChild(floating);positionFloating()}document.addEventListener('click',function(e){const trigger=e.target.closest('[onclick*="toggleActionMenu"]');if(trigger){anchorRect=trigger.getBoundingClientRect();setTimeout(mirrorOpenMenu,0);return}if(e.target.closest('.floating-action-menu')){setTimeout(closeFloating,0);return}closeFloating()},true);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeFloating()});window.addEventListener('resize',closeFloating);window.addEventListener('scroll',closeFloating,true)})();

loadStatus().then(loadTunnels);
